name: cookit
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  animated_text_kit: ^2.2.0
  cached_network_image: ^2.0.0-rc
  firebase_database: ^3.1.1
  cloud_firestore: 0.13.7
  firebase_auth: ^0.15.3+1
  http: ^0.12.0+2
  fluttertoast: ^3.1.3
  google_sign_in: 4.0.1+1
  shared_preferences: 0.5.8
  country_code_picker: 1.4.0
  flutter_phoenix: 0.1.0
  liquid_progress_indicator: 0.3.2
  flutter_tindercard: 0.1.9
  carousel_slider: 2.2.1
  flutter_custom_clippers: 1.1.1
  flutter_webview_plugin: ^0.3.10+1
  email_validator: 1.0.5
  image_picker: 0.6.7+6
  firebase_storage: ^3.0.6
  url_launcher: 5.5.0
  wave: ^0.0.8
  flutter_tts_improved: ^1.0.3
  cupertino_icons: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/splash/1.jpg
    - assets/splash/2.jpg
    - assets/splash/3.jpg
    - assets/splash/4.jpg
    - assets/splash/5.jpg
    - assets/background.jpg
    - assets/google.png
    - assets/facebook.png
    - assets/phone.png
    - assets/images/github-logo.png
    - assets/images/linkedin.png
    - assets/images/twitter.png
    - assets/images/instagram-sketched.png
    - assets/images/whatsapp.png
    - assets/images/night.jpg
    - assets/images/github-logo.png
    - assets/cover.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Livvic
      fonts:
        - asset: assets/fonts/Livvic_Light.ttf
    - family: Aquire
      fonts:
        - asset: assets/fonts/Aquire.otf
        - asset: assets/fonts/AquireLight.otf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
